---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: "https://api.scryfall.com/cards/random?q=game:paper+-is:artseries+{{ scryfall_query }}\r\n"
polling_headers: User-Agent=TRMNL_plugin&Accept=application/json
polling_body: ''
id: 127986
custom_fields:
- keyname: doesnt_matter
  name: About This Plugin
  field_type: author_bio
  description: A random new Magic the Gathering card daily via Scryfall.com
  github_url: https://github.com/thepeopleseason
  learn_more_url: https://bsky.app/profile/thepeopleseason.bsky.social
  email_address: matchstick@gmail.com
- keyname: scryfall_query
  field_type: string
  name: Scryfall Query String
  optional: true
  description: a scryfall query to limit results to the set of cards you'd like to see
name: MTG Card of the Day
refresh_interval: 1440
