---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://weather-worker.lively-paper-cd01.workers.dev/?location={{ user_location }}&metric={{ metric }}
polling_headers: ''
polling_body: ''
id: 131778
custom_fields:
- keyname: user_location
  name: User Location
  field_type: string
- keyname: metric
  field_type: select
  options:
  - Fahrenheit
  - Celsius
  name: Metric
- keyname: time24
  field_type: select
  options:
  - 12-hour time: false
  - 24-hour time: true
  name: Time Display
- keyname: leading_zero
  field_type: select
  default: Include leading zero in hour display
  options:
  - Do not include leading zero in hour display: false
  - Include leading zero in hour display: true
  name: Leading Zero
- keyname: invert
  field_type: select
  default: White text on black background
  options:
  - White text on black background: false
  - Black text on white background: true
  name: Invert (show black text on white background)
- keyname: doesnt_matter
  name: About This Plugin
  field_type: author_bio
  description: Time (sort of) and Weather. Inspired by the Pebble Watchface DIN Time
  github_url: https://github.com/thepeopleseason
  learn_more_url: https://bsky.app/profile/thepeopleseason.bsky.social
  email_address: matchstick@gmail.com
name: DIN Time/Weather
refresh_interval: 15
